# Instructions to install initializer
# Build the initializer
FROM golang:1.9.3 as builder

# Copy in the go src
WORKDIR /go/src/github.com/lwolf/kubereplay
COPY pkg/    pkg/
COPY cmd/    cmd/
COPY vendor/ vendor/

# Build and test the API code
RUN go build -a -o initializer ./cmd/initializer-controller/main.go

# Copy the apiserver into a thin image
FROM ubuntu:latest  
WORKDIR /root/
COPY --from=builder /go/src/github.com/lwolf/kubereplay/initializer .
CMD ["./initializer"]
