/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	time "time"

	replay "github.com/lwolf/kube-replay/pkg/apis/replay"
	clientset_internalversion "github.com/lwolf/kube-replay/pkg/client/clientset/internalversion"
	internalinterfaces "github.com/lwolf/kube-replay/pkg/client/informers/internalversion/internalinterfaces"
	internalversion "github.com/lwolf/kube-replay/pkg/client/listers/replay/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HarvesterInformer provides access to a shared informer and lister for
// Harvesters.
type HarvesterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.HarvesterLister
}

type harvesterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHarvesterInformer constructs a new informer for Harvester type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHarvesterInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHarvesterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHarvesterInformer constructs a new informer for Harvester type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHarvesterInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Kubereplay().Harvesters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Kubereplay().Harvesters(namespace).Watch(options)
			},
		},
		&replay.Harvester{},
		resyncPeriod,
		indexers,
	)
}

func (f *harvesterInformer) defaultInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHarvesterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *harvesterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&replay.Harvester{}, f.defaultInformer)
}

func (f *harvesterInformer) Lister() internalversion.HarvesterLister {
	return internalversion.NewHarvesterLister(f.Informer().GetIndexer())
}
