/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	time "time"

	replay "github.com/lwolf/kube-replay/pkg/apis/replay"
	clientset_internalversion "github.com/lwolf/kube-replay/pkg/client/clientset/internalversion"
	internalinterfaces "github.com/lwolf/kube-replay/pkg/client/informers/internalversion/internalinterfaces"
	internalversion "github.com/lwolf/kube-replay/pkg/client/listers/replay/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RefineryInformer provides access to a shared informer and lister for
// Refineries.
type RefineryInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.RefineryLister
}

type refineryInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRefineryInformer constructs a new informer for Refinery type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRefineryInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRefineryInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRefineryInformer constructs a new informer for Refinery type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRefineryInformer(client clientset_internalversion.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Kubereplay().Refineries(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Kubereplay().Refineries(namespace).Watch(options)
			},
		},
		&replay.Refinery{},
		resyncPeriod,
		indexers,
	)
}

func (f *refineryInformer) defaultInformer(client clientset_internalversion.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRefineryInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *refineryInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&replay.Refinery{}, f.defaultInformer)
}

func (f *refineryInformer) Lister() internalversion.RefineryLister {
	return internalversion.NewRefineryLister(f.Informer().GetIndexer())
}
