// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	replay "github.com/lwolf/kube-replay/pkg/apis/replay"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ElasticsearchSilo_To_replay_ElasticsearchSilo,
		Convert_replay_ElasticsearchSilo_To_v1alpha1_ElasticsearchSilo,
		Convert_v1alpha1_FileSilo_To_replay_FileSilo,
		Convert_replay_FileSilo_To_v1alpha1_FileSilo,
		Convert_v1alpha1_Harvester_To_replay_Harvester,
		Convert_replay_Harvester_To_v1alpha1_Harvester,
		Convert_v1alpha1_HarvesterList_To_replay_HarvesterList,
		Convert_replay_HarvesterList_To_v1alpha1_HarvesterList,
		Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec,
		Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec,
		Convert_v1alpha1_HttpSilo_To_replay_HttpSilo,
		Convert_replay_HttpSilo_To_v1alpha1_HttpSilo,
		Convert_v1alpha1_KafkaSilo_To_replay_KafkaSilo,
		Convert_replay_KafkaSilo_To_v1alpha1_KafkaSilo,
		Convert_v1alpha1_Refinery_To_replay_Refinery,
		Convert_replay_Refinery_To_v1alpha1_Refinery,
		Convert_v1alpha1_RefineryList_To_replay_RefineryList,
		Convert_replay_RefineryList_To_v1alpha1_RefineryList,
		Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec,
		Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec,
		Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus,
		Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus,
		Convert_v1alpha1_RefineryStorage_To_replay_RefineryStorage,
		Convert_replay_RefineryStorage_To_v1alpha1_RefineryStorage,
		Convert_v1alpha1_SiloStatus_To_replay_SiloStatus,
		Convert_replay_SiloStatus_To_v1alpha1_SiloStatus,
		Convert_v1alpha1_StdoutSilo_To_replay_StdoutSilo,
		Convert_replay_StdoutSilo_To_v1alpha1_StdoutSilo,
		Convert_v1alpha1_TcpSilo_To_replay_TcpSilo,
		Convert_replay_TcpSilo_To_v1alpha1_TcpSilo,
	)
}

func autoConvert_v1alpha1_ElasticsearchSilo_To_replay_ElasticsearchSilo(in *ElasticsearchSilo, out *replay.ElasticsearchSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_v1alpha1_ElasticsearchSilo_To_replay_ElasticsearchSilo is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchSilo_To_replay_ElasticsearchSilo(in *ElasticsearchSilo, out *replay.ElasticsearchSilo, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchSilo_To_replay_ElasticsearchSilo(in, out, s)
}

func autoConvert_replay_ElasticsearchSilo_To_v1alpha1_ElasticsearchSilo(in *replay.ElasticsearchSilo, out *ElasticsearchSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_replay_ElasticsearchSilo_To_v1alpha1_ElasticsearchSilo is an autogenerated conversion function.
func Convert_replay_ElasticsearchSilo_To_v1alpha1_ElasticsearchSilo(in *replay.ElasticsearchSilo, out *ElasticsearchSilo, s conversion.Scope) error {
	return autoConvert_replay_ElasticsearchSilo_To_v1alpha1_ElasticsearchSilo(in, out, s)
}

func autoConvert_v1alpha1_FileSilo_To_replay_FileSilo(in *FileSilo, out *replay.FileSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Filename = in.Filename
	out.Append = in.Append
	out.FlushInterval = in.FlushInterval
	out.QueueSize = in.QueueSize
	out.FileLimit = in.FileLimit
	return nil
}

// Convert_v1alpha1_FileSilo_To_replay_FileSilo is an autogenerated conversion function.
func Convert_v1alpha1_FileSilo_To_replay_FileSilo(in *FileSilo, out *replay.FileSilo, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileSilo_To_replay_FileSilo(in, out, s)
}

func autoConvert_replay_FileSilo_To_v1alpha1_FileSilo(in *replay.FileSilo, out *FileSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Filename = in.Filename
	out.Append = in.Append
	out.FlushInterval = in.FlushInterval
	out.QueueSize = in.QueueSize
	out.FileLimit = in.FileLimit
	return nil
}

// Convert_replay_FileSilo_To_v1alpha1_FileSilo is an autogenerated conversion function.
func Convert_replay_FileSilo_To_v1alpha1_FileSilo(in *replay.FileSilo, out *FileSilo, s conversion.Scope) error {
	return autoConvert_replay_FileSilo_To_v1alpha1_FileSilo(in, out, s)
}

func autoConvert_v1alpha1_Harvester_To_replay_Harvester(in *Harvester, out *replay.Harvester, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Harvester_To_replay_Harvester is an autogenerated conversion function.
func Convert_v1alpha1_Harvester_To_replay_Harvester(in *Harvester, out *replay.Harvester, s conversion.Scope) error {
	return autoConvert_v1alpha1_Harvester_To_replay_Harvester(in, out, s)
}

func autoConvert_replay_Harvester_To_v1alpha1_Harvester(in *replay.Harvester, out *Harvester, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Harvester_To_v1alpha1_Harvester is an autogenerated conversion function.
func Convert_replay_Harvester_To_v1alpha1_Harvester(in *replay.Harvester, out *Harvester, s conversion.Scope) error {
	return autoConvert_replay_Harvester_To_v1alpha1_Harvester(in, out, s)
}

func autoConvert_v1alpha1_HarvesterList_To_replay_HarvesterList(in *HarvesterList, out *replay.HarvesterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Harvester)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_HarvesterList_To_replay_HarvesterList is an autogenerated conversion function.
func Convert_v1alpha1_HarvesterList_To_replay_HarvesterList(in *HarvesterList, out *replay.HarvesterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_HarvesterList_To_replay_HarvesterList(in, out, s)
}

func autoConvert_replay_HarvesterList_To_v1alpha1_HarvesterList(in *replay.HarvesterList, out *HarvesterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Harvester)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_HarvesterList_To_v1alpha1_HarvesterList is an autogenerated conversion function.
func Convert_replay_HarvesterList_To_v1alpha1_HarvesterList(in *replay.HarvesterList, out *HarvesterList, s conversion.Scope) error {
	return autoConvert_replay_HarvesterList_To_v1alpha1_HarvesterList(in, out, s)
}

func autoConvert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in *HarvesterSpec, out *replay.HarvesterSpec, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Refinery = in.Refinery
	out.SegmentSize = in.SegmentSize
	return nil
}

// Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec is an autogenerated conversion function.
func Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in *HarvesterSpec, out *replay.HarvesterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in, out, s)
}

func autoConvert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in *replay.HarvesterSpec, out *HarvesterSpec, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Refinery = in.Refinery
	out.SegmentSize = in.SegmentSize
	return nil
}

// Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec is an autogenerated conversion function.
func Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in *replay.HarvesterSpec, out *HarvesterSpec, s conversion.Scope) error {
	return autoConvert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in, out, s)
}

func autoConvert_v1alpha1_HttpSilo_To_replay_HttpSilo(in *HttpSilo, out *replay.HttpSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Debug = in.Debug
	out.ResponseBuffer = in.ResponseBuffer
	return nil
}

// Convert_v1alpha1_HttpSilo_To_replay_HttpSilo is an autogenerated conversion function.
func Convert_v1alpha1_HttpSilo_To_replay_HttpSilo(in *HttpSilo, out *replay.HttpSilo, s conversion.Scope) error {
	return autoConvert_v1alpha1_HttpSilo_To_replay_HttpSilo(in, out, s)
}

func autoConvert_replay_HttpSilo_To_v1alpha1_HttpSilo(in *replay.HttpSilo, out *HttpSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Debug = in.Debug
	out.ResponseBuffer = in.ResponseBuffer
	return nil
}

// Convert_replay_HttpSilo_To_v1alpha1_HttpSilo is an autogenerated conversion function.
func Convert_replay_HttpSilo_To_v1alpha1_HttpSilo(in *replay.HttpSilo, out *HttpSilo, s conversion.Scope) error {
	return autoConvert_replay_HttpSilo_To_v1alpha1_HttpSilo(in, out, s)
}

func autoConvert_v1alpha1_KafkaSilo_To_replay_KafkaSilo(in *KafkaSilo, out *replay.KafkaSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Json = in.Json
	out.Topic = in.Topic
	return nil
}

// Convert_v1alpha1_KafkaSilo_To_replay_KafkaSilo is an autogenerated conversion function.
func Convert_v1alpha1_KafkaSilo_To_replay_KafkaSilo(in *KafkaSilo, out *replay.KafkaSilo, s conversion.Scope) error {
	return autoConvert_v1alpha1_KafkaSilo_To_replay_KafkaSilo(in, out, s)
}

func autoConvert_replay_KafkaSilo_To_v1alpha1_KafkaSilo(in *replay.KafkaSilo, out *KafkaSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Json = in.Json
	out.Topic = in.Topic
	return nil
}

// Convert_replay_KafkaSilo_To_v1alpha1_KafkaSilo is an autogenerated conversion function.
func Convert_replay_KafkaSilo_To_v1alpha1_KafkaSilo(in *replay.KafkaSilo, out *KafkaSilo, s conversion.Scope) error {
	return autoConvert_replay_KafkaSilo_To_v1alpha1_KafkaSilo(in, out, s)
}

func autoConvert_v1alpha1_Refinery_To_replay_Refinery(in *Refinery, out *replay.Refinery, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Refinery_To_replay_Refinery is an autogenerated conversion function.
func Convert_v1alpha1_Refinery_To_replay_Refinery(in *Refinery, out *replay.Refinery, s conversion.Scope) error {
	return autoConvert_v1alpha1_Refinery_To_replay_Refinery(in, out, s)
}

func autoConvert_replay_Refinery_To_v1alpha1_Refinery(in *replay.Refinery, out *Refinery, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Refinery_To_v1alpha1_Refinery is an autogenerated conversion function.
func Convert_replay_Refinery_To_v1alpha1_Refinery(in *replay.Refinery, out *Refinery, s conversion.Scope) error {
	return autoConvert_replay_Refinery_To_v1alpha1_Refinery(in, out, s)
}

func autoConvert_v1alpha1_RefineryList_To_replay_RefineryList(in *RefineryList, out *replay.RefineryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Refinery)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RefineryList_To_replay_RefineryList is an autogenerated conversion function.
func Convert_v1alpha1_RefineryList_To_replay_RefineryList(in *RefineryList, out *replay.RefineryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefineryList_To_replay_RefineryList(in, out, s)
}

func autoConvert_replay_RefineryList_To_v1alpha1_RefineryList(in *replay.RefineryList, out *RefineryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Refinery)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_RefineryList_To_v1alpha1_RefineryList is an autogenerated conversion function.
func Convert_replay_RefineryList_To_v1alpha1_RefineryList(in *replay.RefineryList, out *RefineryList, s conversion.Scope) error {
	return autoConvert_replay_RefineryList_To_v1alpha1_RefineryList(in, out, s)
}

func autoConvert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(in *RefinerySpec, out *replay.RefinerySpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	if err := Convert_v1alpha1_RefineryStorage_To_replay_RefineryStorage(&in.Storage, &out.Storage, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec is an autogenerated conversion function.
func Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(in *RefinerySpec, out *replay.RefinerySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(in, out, s)
}

func autoConvert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(in *replay.RefinerySpec, out *RefinerySpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	if err := Convert_replay_RefineryStorage_To_v1alpha1_RefineryStorage(&in.Storage, &out.Storage, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec is an autogenerated conversion function.
func Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(in *replay.RefinerySpec, out *RefinerySpec, s conversion.Scope) error {
	return autoConvert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(in, out, s)
}

func autoConvert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(in *RefineryStatus, out *replay.RefineryStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus is an autogenerated conversion function.
func Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(in *RefineryStatus, out *replay.RefineryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(in, out, s)
}

func autoConvert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(in *replay.RefineryStatus, out *RefineryStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus is an autogenerated conversion function.
func Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(in *replay.RefineryStatus, out *RefineryStatus, s conversion.Scope) error {
	return autoConvert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(in, out, s)
}

func autoConvert_v1alpha1_RefineryStorage_To_replay_RefineryStorage(in *RefineryStorage, out *replay.RefineryStorage, s conversion.Scope) error {
	if err := Convert_v1alpha1_FileSilo_To_replay_FileSilo(&in.File, &out.File, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TcpSilo_To_replay_TcpSilo(&in.Tcp, &out.Tcp, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_StdoutSilo_To_replay_StdoutSilo(&in.Stdout, &out.Stdout, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_HttpSilo_To_replay_HttpSilo(&in.Http, &out.Http, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ElasticsearchSilo_To_replay_ElasticsearchSilo(&in.Elasticsearch, &out.Elasticsearch, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KafkaSilo_To_replay_KafkaSilo(&in.Kafka, &out.Kafka, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RefineryStorage_To_replay_RefineryStorage is an autogenerated conversion function.
func Convert_v1alpha1_RefineryStorage_To_replay_RefineryStorage(in *RefineryStorage, out *replay.RefineryStorage, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefineryStorage_To_replay_RefineryStorage(in, out, s)
}

func autoConvert_replay_RefineryStorage_To_v1alpha1_RefineryStorage(in *replay.RefineryStorage, out *RefineryStorage, s conversion.Scope) error {
	if err := Convert_replay_FileSilo_To_v1alpha1_FileSilo(&in.File, &out.File, s); err != nil {
		return err
	}
	if err := Convert_replay_TcpSilo_To_v1alpha1_TcpSilo(&in.Tcp, &out.Tcp, s); err != nil {
		return err
	}
	if err := Convert_replay_StdoutSilo_To_v1alpha1_StdoutSilo(&in.Stdout, &out.Stdout, s); err != nil {
		return err
	}
	if err := Convert_replay_HttpSilo_To_v1alpha1_HttpSilo(&in.Http, &out.Http, s); err != nil {
		return err
	}
	if err := Convert_replay_ElasticsearchSilo_To_v1alpha1_ElasticsearchSilo(&in.Elasticsearch, &out.Elasticsearch, s); err != nil {
		return err
	}
	if err := Convert_replay_KafkaSilo_To_v1alpha1_KafkaSilo(&in.Kafka, &out.Kafka, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_RefineryStorage_To_v1alpha1_RefineryStorage is an autogenerated conversion function.
func Convert_replay_RefineryStorage_To_v1alpha1_RefineryStorage(in *replay.RefineryStorage, out *RefineryStorage, s conversion.Scope) error {
	return autoConvert_replay_RefineryStorage_To_v1alpha1_RefineryStorage(in, out, s)
}

func autoConvert_v1alpha1_SiloStatus_To_replay_SiloStatus(in *SiloStatus, out *replay.SiloStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_v1alpha1_SiloStatus_To_replay_SiloStatus is an autogenerated conversion function.
func Convert_v1alpha1_SiloStatus_To_replay_SiloStatus(in *SiloStatus, out *replay.SiloStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloStatus_To_replay_SiloStatus(in, out, s)
}

func autoConvert_replay_SiloStatus_To_v1alpha1_SiloStatus(in *replay.SiloStatus, out *SiloStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_replay_SiloStatus_To_v1alpha1_SiloStatus is an autogenerated conversion function.
func Convert_replay_SiloStatus_To_v1alpha1_SiloStatus(in *replay.SiloStatus, out *SiloStatus, s conversion.Scope) error {
	return autoConvert_replay_SiloStatus_To_v1alpha1_SiloStatus(in, out, s)
}

func autoConvert_v1alpha1_StdoutSilo_To_replay_StdoutSilo(in *StdoutSilo, out *replay.StdoutSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_StdoutSilo_To_replay_StdoutSilo is an autogenerated conversion function.
func Convert_v1alpha1_StdoutSilo_To_replay_StdoutSilo(in *StdoutSilo, out *replay.StdoutSilo, s conversion.Scope) error {
	return autoConvert_v1alpha1_StdoutSilo_To_replay_StdoutSilo(in, out, s)
}

func autoConvert_replay_StdoutSilo_To_v1alpha1_StdoutSilo(in *replay.StdoutSilo, out *StdoutSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_replay_StdoutSilo_To_v1alpha1_StdoutSilo is an autogenerated conversion function.
func Convert_replay_StdoutSilo_To_v1alpha1_StdoutSilo(in *replay.StdoutSilo, out *StdoutSilo, s conversion.Scope) error {
	return autoConvert_replay_StdoutSilo_To_v1alpha1_StdoutSilo(in, out, s)
}

func autoConvert_v1alpha1_TcpSilo_To_replay_TcpSilo(in *TcpSilo, out *replay.TcpSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_v1alpha1_TcpSilo_To_replay_TcpSilo is an autogenerated conversion function.
func Convert_v1alpha1_TcpSilo_To_replay_TcpSilo(in *TcpSilo, out *replay.TcpSilo, s conversion.Scope) error {
	return autoConvert_v1alpha1_TcpSilo_To_replay_TcpSilo(in, out, s)
}

func autoConvert_replay_TcpSilo_To_v1alpha1_TcpSilo(in *replay.TcpSilo, out *TcpSilo, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_replay_TcpSilo_To_v1alpha1_TcpSilo is an autogenerated conversion function.
func Convert_replay_TcpSilo_To_v1alpha1_TcpSilo(in *replay.TcpSilo, out *TcpSilo, s conversion.Scope) error {
	return autoConvert_replay_TcpSilo_To_v1alpha1_TcpSilo(in, out, s)
}
