// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	replay "github.com/lwolf/kube-replay/pkg/apis/replay"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Harvester_To_replay_Harvester,
		Convert_replay_Harvester_To_v1alpha1_Harvester,
		Convert_v1alpha1_HarvesterList_To_replay_HarvesterList,
		Convert_replay_HarvesterList_To_v1alpha1_HarvesterList,
		Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec,
		Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec,
		Convert_v1alpha1_Silo_To_replay_Silo,
		Convert_replay_Silo_To_v1alpha1_Silo,
		Convert_v1alpha1_SiloElasticsearchOutput_To_replay_SiloElasticsearchOutput,
		Convert_replay_SiloElasticsearchOutput_To_v1alpha1_SiloElasticsearchOutput,
		Convert_v1alpha1_SiloFileOutput_To_replay_SiloFileOutput,
		Convert_replay_SiloFileOutput_To_v1alpha1_SiloFileOutput,
		Convert_v1alpha1_SiloHttpOutput_To_replay_SiloHttpOutput,
		Convert_replay_SiloHttpOutput_To_v1alpha1_SiloHttpOutput,
		Convert_v1alpha1_SiloKafkaOutput_To_replay_SiloKafkaOutput,
		Convert_replay_SiloKafkaOutput_To_v1alpha1_SiloKafkaOutput,
		Convert_v1alpha1_SiloList_To_replay_SiloList,
		Convert_replay_SiloList_To_v1alpha1_SiloList,
		Convert_v1alpha1_SiloSpec_To_replay_SiloSpec,
		Convert_replay_SiloSpec_To_v1alpha1_SiloSpec,
		Convert_v1alpha1_SiloStatus_To_replay_SiloStatus,
		Convert_replay_SiloStatus_To_v1alpha1_SiloStatus,
		Convert_v1alpha1_SiloStdoutOutput_To_replay_SiloStdoutOutput,
		Convert_replay_SiloStdoutOutput_To_v1alpha1_SiloStdoutOutput,
		Convert_v1alpha1_SiloTcpOutput_To_replay_SiloTcpOutput,
		Convert_replay_SiloTcpOutput_To_v1alpha1_SiloTcpOutput,
	)
}

func autoConvert_v1alpha1_Harvester_To_replay_Harvester(in *Harvester, out *replay.Harvester, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Harvester_To_replay_Harvester is an autogenerated conversion function.
func Convert_v1alpha1_Harvester_To_replay_Harvester(in *Harvester, out *replay.Harvester, s conversion.Scope) error {
	return autoConvert_v1alpha1_Harvester_To_replay_Harvester(in, out, s)
}

func autoConvert_replay_Harvester_To_v1alpha1_Harvester(in *replay.Harvester, out *Harvester, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Harvester_To_v1alpha1_Harvester is an autogenerated conversion function.
func Convert_replay_Harvester_To_v1alpha1_Harvester(in *replay.Harvester, out *Harvester, s conversion.Scope) error {
	return autoConvert_replay_Harvester_To_v1alpha1_Harvester(in, out, s)
}

func autoConvert_v1alpha1_HarvesterList_To_replay_HarvesterList(in *HarvesterList, out *replay.HarvesterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Harvester)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_HarvesterList_To_replay_HarvesterList is an autogenerated conversion function.
func Convert_v1alpha1_HarvesterList_To_replay_HarvesterList(in *HarvesterList, out *replay.HarvesterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_HarvesterList_To_replay_HarvesterList(in, out, s)
}

func autoConvert_replay_HarvesterList_To_v1alpha1_HarvesterList(in *replay.HarvesterList, out *HarvesterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Harvester)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_HarvesterList_To_v1alpha1_HarvesterList is an autogenerated conversion function.
func Convert_replay_HarvesterList_To_v1alpha1_HarvesterList(in *replay.HarvesterList, out *HarvesterList, s conversion.Scope) error {
	return autoConvert_replay_HarvesterList_To_v1alpha1_HarvesterList(in, out, s)
}

func autoConvert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in *HarvesterSpec, out *replay.HarvesterSpec, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Silo = in.Silo
	out.SegmentSize = in.SegmentSize
	return nil
}

// Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec is an autogenerated conversion function.
func Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in *HarvesterSpec, out *replay.HarvesterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in, out, s)
}

func autoConvert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in *replay.HarvesterSpec, out *HarvesterSpec, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Silo = in.Silo
	out.SegmentSize = in.SegmentSize
	return nil
}

// Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec is an autogenerated conversion function.
func Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in *replay.HarvesterSpec, out *HarvesterSpec, s conversion.Scope) error {
	return autoConvert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in, out, s)
}

func autoConvert_v1alpha1_Silo_To_replay_Silo(in *Silo, out *replay.Silo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SiloSpec_To_replay_SiloSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SiloStatus_To_replay_SiloStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Silo_To_replay_Silo is an autogenerated conversion function.
func Convert_v1alpha1_Silo_To_replay_Silo(in *Silo, out *replay.Silo, s conversion.Scope) error {
	return autoConvert_v1alpha1_Silo_To_replay_Silo(in, out, s)
}

func autoConvert_replay_Silo_To_v1alpha1_Silo(in *replay.Silo, out *Silo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_SiloSpec_To_v1alpha1_SiloSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_replay_SiloStatus_To_v1alpha1_SiloStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Silo_To_v1alpha1_Silo is an autogenerated conversion function.
func Convert_replay_Silo_To_v1alpha1_Silo(in *replay.Silo, out *Silo, s conversion.Scope) error {
	return autoConvert_replay_Silo_To_v1alpha1_Silo(in, out, s)
}

func autoConvert_v1alpha1_SiloElasticsearchOutput_To_replay_SiloElasticsearchOutput(in *SiloElasticsearchOutput, out *replay.SiloElasticsearchOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_v1alpha1_SiloElasticsearchOutput_To_replay_SiloElasticsearchOutput is an autogenerated conversion function.
func Convert_v1alpha1_SiloElasticsearchOutput_To_replay_SiloElasticsearchOutput(in *SiloElasticsearchOutput, out *replay.SiloElasticsearchOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloElasticsearchOutput_To_replay_SiloElasticsearchOutput(in, out, s)
}

func autoConvert_replay_SiloElasticsearchOutput_To_v1alpha1_SiloElasticsearchOutput(in *replay.SiloElasticsearchOutput, out *SiloElasticsearchOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_replay_SiloElasticsearchOutput_To_v1alpha1_SiloElasticsearchOutput is an autogenerated conversion function.
func Convert_replay_SiloElasticsearchOutput_To_v1alpha1_SiloElasticsearchOutput(in *replay.SiloElasticsearchOutput, out *SiloElasticsearchOutput, s conversion.Scope) error {
	return autoConvert_replay_SiloElasticsearchOutput_To_v1alpha1_SiloElasticsearchOutput(in, out, s)
}

func autoConvert_v1alpha1_SiloFileOutput_To_replay_SiloFileOutput(in *SiloFileOutput, out *replay.SiloFileOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Filename = in.Filename
	out.Append = in.Append
	out.FlushInterval = in.FlushInterval
	out.QueueSize = in.QueueSize
	out.FileLimit = in.FileLimit
	return nil
}

// Convert_v1alpha1_SiloFileOutput_To_replay_SiloFileOutput is an autogenerated conversion function.
func Convert_v1alpha1_SiloFileOutput_To_replay_SiloFileOutput(in *SiloFileOutput, out *replay.SiloFileOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloFileOutput_To_replay_SiloFileOutput(in, out, s)
}

func autoConvert_replay_SiloFileOutput_To_v1alpha1_SiloFileOutput(in *replay.SiloFileOutput, out *SiloFileOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Filename = in.Filename
	out.Append = in.Append
	out.FlushInterval = in.FlushInterval
	out.QueueSize = in.QueueSize
	out.FileLimit = in.FileLimit
	return nil
}

// Convert_replay_SiloFileOutput_To_v1alpha1_SiloFileOutput is an autogenerated conversion function.
func Convert_replay_SiloFileOutput_To_v1alpha1_SiloFileOutput(in *replay.SiloFileOutput, out *SiloFileOutput, s conversion.Scope) error {
	return autoConvert_replay_SiloFileOutput_To_v1alpha1_SiloFileOutput(in, out, s)
}

func autoConvert_v1alpha1_SiloHttpOutput_To_replay_SiloHttpOutput(in *SiloHttpOutput, out *replay.SiloHttpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Debug = in.Debug
	out.ResponseBuffer = in.ResponseBuffer
	return nil
}

// Convert_v1alpha1_SiloHttpOutput_To_replay_SiloHttpOutput is an autogenerated conversion function.
func Convert_v1alpha1_SiloHttpOutput_To_replay_SiloHttpOutput(in *SiloHttpOutput, out *replay.SiloHttpOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloHttpOutput_To_replay_SiloHttpOutput(in, out, s)
}

func autoConvert_replay_SiloHttpOutput_To_v1alpha1_SiloHttpOutput(in *replay.SiloHttpOutput, out *SiloHttpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Debug = in.Debug
	out.ResponseBuffer = in.ResponseBuffer
	return nil
}

// Convert_replay_SiloHttpOutput_To_v1alpha1_SiloHttpOutput is an autogenerated conversion function.
func Convert_replay_SiloHttpOutput_To_v1alpha1_SiloHttpOutput(in *replay.SiloHttpOutput, out *SiloHttpOutput, s conversion.Scope) error {
	return autoConvert_replay_SiloHttpOutput_To_v1alpha1_SiloHttpOutput(in, out, s)
}

func autoConvert_v1alpha1_SiloKafkaOutput_To_replay_SiloKafkaOutput(in *SiloKafkaOutput, out *replay.SiloKafkaOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Json = in.Json
	out.Topic = in.Topic
	return nil
}

// Convert_v1alpha1_SiloKafkaOutput_To_replay_SiloKafkaOutput is an autogenerated conversion function.
func Convert_v1alpha1_SiloKafkaOutput_To_replay_SiloKafkaOutput(in *SiloKafkaOutput, out *replay.SiloKafkaOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloKafkaOutput_To_replay_SiloKafkaOutput(in, out, s)
}

func autoConvert_replay_SiloKafkaOutput_To_v1alpha1_SiloKafkaOutput(in *replay.SiloKafkaOutput, out *SiloKafkaOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Json = in.Json
	out.Topic = in.Topic
	return nil
}

// Convert_replay_SiloKafkaOutput_To_v1alpha1_SiloKafkaOutput is an autogenerated conversion function.
func Convert_replay_SiloKafkaOutput_To_v1alpha1_SiloKafkaOutput(in *replay.SiloKafkaOutput, out *SiloKafkaOutput, s conversion.Scope) error {
	return autoConvert_replay_SiloKafkaOutput_To_v1alpha1_SiloKafkaOutput(in, out, s)
}

func autoConvert_v1alpha1_SiloList_To_replay_SiloList(in *SiloList, out *replay.SiloList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Silo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SiloList_To_replay_SiloList is an autogenerated conversion function.
func Convert_v1alpha1_SiloList_To_replay_SiloList(in *SiloList, out *replay.SiloList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloList_To_replay_SiloList(in, out, s)
}

func autoConvert_replay_SiloList_To_v1alpha1_SiloList(in *replay.SiloList, out *SiloList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Silo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_SiloList_To_v1alpha1_SiloList is an autogenerated conversion function.
func Convert_replay_SiloList_To_v1alpha1_SiloList(in *replay.SiloList, out *SiloList, s conversion.Scope) error {
	return autoConvert_replay_SiloList_To_v1alpha1_SiloList(in, out, s)
}

func autoConvert_v1alpha1_SiloSpec_To_replay_SiloSpec(in *SiloSpec, out *replay.SiloSpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Output, &out.Output, 0); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SiloSpec_To_replay_SiloSpec is an autogenerated conversion function.
func Convert_v1alpha1_SiloSpec_To_replay_SiloSpec(in *SiloSpec, out *replay.SiloSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloSpec_To_replay_SiloSpec(in, out, s)
}

func autoConvert_replay_SiloSpec_To_v1alpha1_SiloSpec(in *replay.SiloSpec, out *SiloSpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Output, &out.Output, 0); err != nil {
		return err
	}
	return nil
}

// Convert_replay_SiloSpec_To_v1alpha1_SiloSpec is an autogenerated conversion function.
func Convert_replay_SiloSpec_To_v1alpha1_SiloSpec(in *replay.SiloSpec, out *SiloSpec, s conversion.Scope) error {
	return autoConvert_replay_SiloSpec_To_v1alpha1_SiloSpec(in, out, s)
}

func autoConvert_v1alpha1_SiloStatus_To_replay_SiloStatus(in *SiloStatus, out *replay.SiloStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_v1alpha1_SiloStatus_To_replay_SiloStatus is an autogenerated conversion function.
func Convert_v1alpha1_SiloStatus_To_replay_SiloStatus(in *SiloStatus, out *replay.SiloStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloStatus_To_replay_SiloStatus(in, out, s)
}

func autoConvert_replay_SiloStatus_To_v1alpha1_SiloStatus(in *replay.SiloStatus, out *SiloStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_replay_SiloStatus_To_v1alpha1_SiloStatus is an autogenerated conversion function.
func Convert_replay_SiloStatus_To_v1alpha1_SiloStatus(in *replay.SiloStatus, out *SiloStatus, s conversion.Scope) error {
	return autoConvert_replay_SiloStatus_To_v1alpha1_SiloStatus(in, out, s)
}

func autoConvert_v1alpha1_SiloStdoutOutput_To_replay_SiloStdoutOutput(in *SiloStdoutOutput, out *replay.SiloStdoutOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_SiloStdoutOutput_To_replay_SiloStdoutOutput is an autogenerated conversion function.
func Convert_v1alpha1_SiloStdoutOutput_To_replay_SiloStdoutOutput(in *SiloStdoutOutput, out *replay.SiloStdoutOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloStdoutOutput_To_replay_SiloStdoutOutput(in, out, s)
}

func autoConvert_replay_SiloStdoutOutput_To_v1alpha1_SiloStdoutOutput(in *replay.SiloStdoutOutput, out *SiloStdoutOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_replay_SiloStdoutOutput_To_v1alpha1_SiloStdoutOutput is an autogenerated conversion function.
func Convert_replay_SiloStdoutOutput_To_v1alpha1_SiloStdoutOutput(in *replay.SiloStdoutOutput, out *SiloStdoutOutput, s conversion.Scope) error {
	return autoConvert_replay_SiloStdoutOutput_To_v1alpha1_SiloStdoutOutput(in, out, s)
}

func autoConvert_v1alpha1_SiloTcpOutput_To_replay_SiloTcpOutput(in *SiloTcpOutput, out *replay.SiloTcpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_v1alpha1_SiloTcpOutput_To_replay_SiloTcpOutput is an autogenerated conversion function.
func Convert_v1alpha1_SiloTcpOutput_To_replay_SiloTcpOutput(in *SiloTcpOutput, out *replay.SiloTcpOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloTcpOutput_To_replay_SiloTcpOutput(in, out, s)
}

func autoConvert_replay_SiloTcpOutput_To_v1alpha1_SiloTcpOutput(in *replay.SiloTcpOutput, out *SiloTcpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_replay_SiloTcpOutput_To_v1alpha1_SiloTcpOutput is an autogenerated conversion function.
func Convert_replay_SiloTcpOutput_To_v1alpha1_SiloTcpOutput(in *replay.SiloTcpOutput, out *SiloTcpOutput, s conversion.Scope) error {
	return autoConvert_replay_SiloTcpOutput_To_v1alpha1_SiloTcpOutput(in, out, s)
}
