// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	unsafe "unsafe"

	replay "github.com/lwolf/kube-replay/pkg/apis/replay"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_ElasticsearchOutput_To_replay_ElasticsearchOutput,
		Convert_replay_ElasticsearchOutput_To_v1alpha1_ElasticsearchOutput,
		Convert_v1alpha1_FileOutput_To_replay_FileOutput,
		Convert_replay_FileOutput_To_v1alpha1_FileOutput,
		Convert_v1alpha1_Harvester_To_replay_Harvester,
		Convert_replay_Harvester_To_v1alpha1_Harvester,
		Convert_v1alpha1_HarvesterList_To_replay_HarvesterList,
		Convert_replay_HarvesterList_To_v1alpha1_HarvesterList,
		Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec,
		Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec,
		Convert_v1alpha1_HttpOutput_To_replay_HttpOutput,
		Convert_replay_HttpOutput_To_v1alpha1_HttpOutput,
		Convert_v1alpha1_KafkaOutput_To_replay_KafkaOutput,
		Convert_replay_KafkaOutput_To_v1alpha1_KafkaOutput,
		Convert_v1alpha1_Refinery_To_replay_Refinery,
		Convert_replay_Refinery_To_v1alpha1_Refinery,
		Convert_v1alpha1_RefineryList_To_replay_RefineryList,
		Convert_replay_RefineryList_To_v1alpha1_RefineryList,
		Convert_v1alpha1_RefineryOutput_To_replay_RefineryOutput,
		Convert_replay_RefineryOutput_To_v1alpha1_RefineryOutput,
		Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec,
		Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec,
		Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus,
		Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus,
		Convert_v1alpha1_Silo_To_replay_Silo,
		Convert_replay_Silo_To_v1alpha1_Silo,
		Convert_v1alpha1_SiloList_To_replay_SiloList,
		Convert_replay_SiloList_To_v1alpha1_SiloList,
		Convert_v1alpha1_SiloSpec_To_replay_SiloSpec,
		Convert_replay_SiloSpec_To_v1alpha1_SiloSpec,
		Convert_v1alpha1_SiloStatus_To_replay_SiloStatus,
		Convert_replay_SiloStatus_To_v1alpha1_SiloStatus,
		Convert_v1alpha1_StdoutOutput_To_replay_StdoutOutput,
		Convert_replay_StdoutOutput_To_v1alpha1_StdoutOutput,
		Convert_v1alpha1_TcpOutput_To_replay_TcpOutput,
		Convert_replay_TcpOutput_To_v1alpha1_TcpOutput,
	)
}

func autoConvert_v1alpha1_ElasticsearchOutput_To_replay_ElasticsearchOutput(in *ElasticsearchOutput, out *replay.ElasticsearchOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_v1alpha1_ElasticsearchOutput_To_replay_ElasticsearchOutput is an autogenerated conversion function.
func Convert_v1alpha1_ElasticsearchOutput_To_replay_ElasticsearchOutput(in *ElasticsearchOutput, out *replay.ElasticsearchOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_ElasticsearchOutput_To_replay_ElasticsearchOutput(in, out, s)
}

func autoConvert_replay_ElasticsearchOutput_To_v1alpha1_ElasticsearchOutput(in *replay.ElasticsearchOutput, out *ElasticsearchOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_replay_ElasticsearchOutput_To_v1alpha1_ElasticsearchOutput is an autogenerated conversion function.
func Convert_replay_ElasticsearchOutput_To_v1alpha1_ElasticsearchOutput(in *replay.ElasticsearchOutput, out *ElasticsearchOutput, s conversion.Scope) error {
	return autoConvert_replay_ElasticsearchOutput_To_v1alpha1_ElasticsearchOutput(in, out, s)
}

func autoConvert_v1alpha1_FileOutput_To_replay_FileOutput(in *FileOutput, out *replay.FileOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Filename = in.Filename
	out.Append = in.Append
	out.FlushInterval = in.FlushInterval
	out.QueueSize = in.QueueSize
	out.FileLimit = in.FileLimit
	return nil
}

// Convert_v1alpha1_FileOutput_To_replay_FileOutput is an autogenerated conversion function.
func Convert_v1alpha1_FileOutput_To_replay_FileOutput(in *FileOutput, out *replay.FileOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_FileOutput_To_replay_FileOutput(in, out, s)
}

func autoConvert_replay_FileOutput_To_v1alpha1_FileOutput(in *replay.FileOutput, out *FileOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Filename = in.Filename
	out.Append = in.Append
	out.FlushInterval = in.FlushInterval
	out.QueueSize = in.QueueSize
	out.FileLimit = in.FileLimit
	return nil
}

// Convert_replay_FileOutput_To_v1alpha1_FileOutput is an autogenerated conversion function.
func Convert_replay_FileOutput_To_v1alpha1_FileOutput(in *replay.FileOutput, out *FileOutput, s conversion.Scope) error {
	return autoConvert_replay_FileOutput_To_v1alpha1_FileOutput(in, out, s)
}

func autoConvert_v1alpha1_Harvester_To_replay_Harvester(in *Harvester, out *replay.Harvester, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Harvester_To_replay_Harvester is an autogenerated conversion function.
func Convert_v1alpha1_Harvester_To_replay_Harvester(in *Harvester, out *replay.Harvester, s conversion.Scope) error {
	return autoConvert_v1alpha1_Harvester_To_replay_Harvester(in, out, s)
}

func autoConvert_replay_Harvester_To_v1alpha1_Harvester(in *replay.Harvester, out *Harvester, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Harvester_To_v1alpha1_Harvester is an autogenerated conversion function.
func Convert_replay_Harvester_To_v1alpha1_Harvester(in *replay.Harvester, out *Harvester, s conversion.Scope) error {
	return autoConvert_replay_Harvester_To_v1alpha1_Harvester(in, out, s)
}

func autoConvert_v1alpha1_HarvesterList_To_replay_HarvesterList(in *HarvesterList, out *replay.HarvesterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Harvester)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_HarvesterList_To_replay_HarvesterList is an autogenerated conversion function.
func Convert_v1alpha1_HarvesterList_To_replay_HarvesterList(in *HarvesterList, out *replay.HarvesterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_HarvesterList_To_replay_HarvesterList(in, out, s)
}

func autoConvert_replay_HarvesterList_To_v1alpha1_HarvesterList(in *replay.HarvesterList, out *HarvesterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Harvester)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_HarvesterList_To_v1alpha1_HarvesterList is an autogenerated conversion function.
func Convert_replay_HarvesterList_To_v1alpha1_HarvesterList(in *replay.HarvesterList, out *HarvesterList, s conversion.Scope) error {
	return autoConvert_replay_HarvesterList_To_v1alpha1_HarvesterList(in, out, s)
}

func autoConvert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in *HarvesterSpec, out *replay.HarvesterSpec, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Silo = in.Silo
	out.SegmentSize = in.SegmentSize
	return nil
}

// Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec is an autogenerated conversion function.
func Convert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in *HarvesterSpec, out *replay.HarvesterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_HarvesterSpec_To_replay_HarvesterSpec(in, out, s)
}

func autoConvert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in *replay.HarvesterSpec, out *HarvesterSpec, s conversion.Scope) error {
	out.Selector = in.Selector
	out.Silo = in.Silo
	out.SegmentSize = in.SegmentSize
	return nil
}

// Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec is an autogenerated conversion function.
func Convert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in *replay.HarvesterSpec, out *HarvesterSpec, s conversion.Scope) error {
	return autoConvert_replay_HarvesterSpec_To_v1alpha1_HarvesterSpec(in, out, s)
}

func autoConvert_v1alpha1_HttpOutput_To_replay_HttpOutput(in *HttpOutput, out *replay.HttpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Debug = in.Debug
	out.ResponseBuffer = in.ResponseBuffer
	return nil
}

// Convert_v1alpha1_HttpOutput_To_replay_HttpOutput is an autogenerated conversion function.
func Convert_v1alpha1_HttpOutput_To_replay_HttpOutput(in *HttpOutput, out *replay.HttpOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_HttpOutput_To_replay_HttpOutput(in, out, s)
}

func autoConvert_replay_HttpOutput_To_v1alpha1_HttpOutput(in *replay.HttpOutput, out *HttpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Debug = in.Debug
	out.ResponseBuffer = in.ResponseBuffer
	return nil
}

// Convert_replay_HttpOutput_To_v1alpha1_HttpOutput is an autogenerated conversion function.
func Convert_replay_HttpOutput_To_v1alpha1_HttpOutput(in *replay.HttpOutput, out *HttpOutput, s conversion.Scope) error {
	return autoConvert_replay_HttpOutput_To_v1alpha1_HttpOutput(in, out, s)
}

func autoConvert_v1alpha1_KafkaOutput_To_replay_KafkaOutput(in *KafkaOutput, out *replay.KafkaOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Json = in.Json
	out.Topic = in.Topic
	return nil
}

// Convert_v1alpha1_KafkaOutput_To_replay_KafkaOutput is an autogenerated conversion function.
func Convert_v1alpha1_KafkaOutput_To_replay_KafkaOutput(in *KafkaOutput, out *replay.KafkaOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_KafkaOutput_To_replay_KafkaOutput(in, out, s)
}

func autoConvert_replay_KafkaOutput_To_v1alpha1_KafkaOutput(in *replay.KafkaOutput, out *KafkaOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	out.Json = in.Json
	out.Topic = in.Topic
	return nil
}

// Convert_replay_KafkaOutput_To_v1alpha1_KafkaOutput is an autogenerated conversion function.
func Convert_replay_KafkaOutput_To_v1alpha1_KafkaOutput(in *replay.KafkaOutput, out *KafkaOutput, s conversion.Scope) error {
	return autoConvert_replay_KafkaOutput_To_v1alpha1_KafkaOutput(in, out, s)
}

func autoConvert_v1alpha1_Refinery_To_replay_Refinery(in *Refinery, out *replay.Refinery, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Refinery_To_replay_Refinery is an autogenerated conversion function.
func Convert_v1alpha1_Refinery_To_replay_Refinery(in *Refinery, out *replay.Refinery, s conversion.Scope) error {
	return autoConvert_v1alpha1_Refinery_To_replay_Refinery(in, out, s)
}

func autoConvert_replay_Refinery_To_v1alpha1_Refinery(in *replay.Refinery, out *Refinery, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Refinery_To_v1alpha1_Refinery is an autogenerated conversion function.
func Convert_replay_Refinery_To_v1alpha1_Refinery(in *replay.Refinery, out *Refinery, s conversion.Scope) error {
	return autoConvert_replay_Refinery_To_v1alpha1_Refinery(in, out, s)
}

func autoConvert_v1alpha1_RefineryList_To_replay_RefineryList(in *RefineryList, out *replay.RefineryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Refinery)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RefineryList_To_replay_RefineryList is an autogenerated conversion function.
func Convert_v1alpha1_RefineryList_To_replay_RefineryList(in *RefineryList, out *replay.RefineryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefineryList_To_replay_RefineryList(in, out, s)
}

func autoConvert_replay_RefineryList_To_v1alpha1_RefineryList(in *replay.RefineryList, out *RefineryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Refinery)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_RefineryList_To_v1alpha1_RefineryList is an autogenerated conversion function.
func Convert_replay_RefineryList_To_v1alpha1_RefineryList(in *replay.RefineryList, out *RefineryList, s conversion.Scope) error {
	return autoConvert_replay_RefineryList_To_v1alpha1_RefineryList(in, out, s)
}

func autoConvert_v1alpha1_RefineryOutput_To_replay_RefineryOutput(in *RefineryOutput, out *replay.RefineryOutput, s conversion.Scope) error {
	if err := Convert_v1alpha1_FileOutput_To_replay_FileOutput(&in.File, &out.File, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TcpOutput_To_replay_TcpOutput(&in.Tcp, &out.Tcp, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_StdoutOutput_To_replay_StdoutOutput(&in.Stdout, &out.Stdout, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_HttpOutput_To_replay_HttpOutput(&in.Http, &out.Http, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ElasticsearchOutput_To_replay_ElasticsearchOutput(&in.Elasticsearch, &out.Elasticsearch, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_KafkaOutput_To_replay_KafkaOutput(&in.Kafka, &out.Kafka, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RefineryOutput_To_replay_RefineryOutput is an autogenerated conversion function.
func Convert_v1alpha1_RefineryOutput_To_replay_RefineryOutput(in *RefineryOutput, out *replay.RefineryOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefineryOutput_To_replay_RefineryOutput(in, out, s)
}

func autoConvert_replay_RefineryOutput_To_v1alpha1_RefineryOutput(in *replay.RefineryOutput, out *RefineryOutput, s conversion.Scope) error {
	if err := Convert_replay_FileOutput_To_v1alpha1_FileOutput(&in.File, &out.File, s); err != nil {
		return err
	}
	if err := Convert_replay_TcpOutput_To_v1alpha1_TcpOutput(&in.Tcp, &out.Tcp, s); err != nil {
		return err
	}
	if err := Convert_replay_StdoutOutput_To_v1alpha1_StdoutOutput(&in.Stdout, &out.Stdout, s); err != nil {
		return err
	}
	if err := Convert_replay_HttpOutput_To_v1alpha1_HttpOutput(&in.Http, &out.Http, s); err != nil {
		return err
	}
	if err := Convert_replay_ElasticsearchOutput_To_v1alpha1_ElasticsearchOutput(&in.Elasticsearch, &out.Elasticsearch, s); err != nil {
		return err
	}
	if err := Convert_replay_KafkaOutput_To_v1alpha1_KafkaOutput(&in.Kafka, &out.Kafka, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_RefineryOutput_To_v1alpha1_RefineryOutput is an autogenerated conversion function.
func Convert_replay_RefineryOutput_To_v1alpha1_RefineryOutput(in *replay.RefineryOutput, out *RefineryOutput, s conversion.Scope) error {
	return autoConvert_replay_RefineryOutput_To_v1alpha1_RefineryOutput(in, out, s)
}

func autoConvert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(in *RefinerySpec, out *replay.RefinerySpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	if err := Convert_v1alpha1_RefineryOutput_To_replay_RefineryOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec is an autogenerated conversion function.
func Convert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(in *RefinerySpec, out *replay.RefinerySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefinerySpec_To_replay_RefinerySpec(in, out, s)
}

func autoConvert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(in *replay.RefinerySpec, out *RefinerySpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	if err := Convert_replay_RefineryOutput_To_v1alpha1_RefineryOutput(&in.Output, &out.Output, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec is an autogenerated conversion function.
func Convert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(in *replay.RefinerySpec, out *RefinerySpec, s conversion.Scope) error {
	return autoConvert_replay_RefinerySpec_To_v1alpha1_RefinerySpec(in, out, s)
}

func autoConvert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(in *RefineryStatus, out *replay.RefineryStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus is an autogenerated conversion function.
func Convert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(in *RefineryStatus, out *replay.RefineryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RefineryStatus_To_replay_RefineryStatus(in, out, s)
}

func autoConvert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(in *replay.RefineryStatus, out *RefineryStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus is an autogenerated conversion function.
func Convert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(in *replay.RefineryStatus, out *RefineryStatus, s conversion.Scope) error {
	return autoConvert_replay_RefineryStatus_To_v1alpha1_RefineryStatus(in, out, s)
}

func autoConvert_v1alpha1_Silo_To_replay_Silo(in *Silo, out *replay.Silo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_SiloSpec_To_replay_SiloSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_SiloStatus_To_replay_SiloStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Silo_To_replay_Silo is an autogenerated conversion function.
func Convert_v1alpha1_Silo_To_replay_Silo(in *Silo, out *replay.Silo, s conversion.Scope) error {
	return autoConvert_v1alpha1_Silo_To_replay_Silo(in, out, s)
}

func autoConvert_replay_Silo_To_v1alpha1_Silo(in *replay.Silo, out *Silo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_replay_SiloSpec_To_v1alpha1_SiloSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_replay_SiloStatus_To_v1alpha1_SiloStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_replay_Silo_To_v1alpha1_Silo is an autogenerated conversion function.
func Convert_replay_Silo_To_v1alpha1_Silo(in *replay.Silo, out *Silo, s conversion.Scope) error {
	return autoConvert_replay_Silo_To_v1alpha1_Silo(in, out, s)
}

func autoConvert_v1alpha1_SiloList_To_replay_SiloList(in *SiloList, out *replay.SiloList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]replay.Silo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_SiloList_To_replay_SiloList is an autogenerated conversion function.
func Convert_v1alpha1_SiloList_To_replay_SiloList(in *SiloList, out *replay.SiloList, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloList_To_replay_SiloList(in, out, s)
}

func autoConvert_replay_SiloList_To_v1alpha1_SiloList(in *replay.SiloList, out *SiloList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Silo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_replay_SiloList_To_v1alpha1_SiloList is an autogenerated conversion function.
func Convert_replay_SiloList_To_v1alpha1_SiloList(in *replay.SiloList, out *SiloList, s conversion.Scope) error {
	return autoConvert_replay_SiloList_To_v1alpha1_SiloList(in, out, s)
}

func autoConvert_v1alpha1_SiloSpec_To_replay_SiloSpec(in *SiloSpec, out *replay.SiloSpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Output, &out.Output, 0); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SiloSpec_To_replay_SiloSpec is an autogenerated conversion function.
func Convert_v1alpha1_SiloSpec_To_replay_SiloSpec(in *SiloSpec, out *replay.SiloSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloSpec_To_replay_SiloSpec(in, out, s)
}

func autoConvert_replay_SiloSpec_To_v1alpha1_SiloSpec(in *replay.SiloSpec, out *SiloSpec, s conversion.Scope) error {
	out.Workers = in.Workers
	out.Timeout = in.Timeout
	// TODO: Inefficient conversion - can we improve it?
	if err := s.Convert(&in.Output, &out.Output, 0); err != nil {
		return err
	}
	return nil
}

// Convert_replay_SiloSpec_To_v1alpha1_SiloSpec is an autogenerated conversion function.
func Convert_replay_SiloSpec_To_v1alpha1_SiloSpec(in *replay.SiloSpec, out *SiloSpec, s conversion.Scope) error {
	return autoConvert_replay_SiloSpec_To_v1alpha1_SiloSpec(in, out, s)
}

func autoConvert_v1alpha1_SiloStatus_To_replay_SiloStatus(in *SiloStatus, out *replay.SiloStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_v1alpha1_SiloStatus_To_replay_SiloStatus is an autogenerated conversion function.
func Convert_v1alpha1_SiloStatus_To_replay_SiloStatus(in *SiloStatus, out *replay.SiloStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_SiloStatus_To_replay_SiloStatus(in, out, s)
}

func autoConvert_replay_SiloStatus_To_v1alpha1_SiloStatus(in *replay.SiloStatus, out *SiloStatus, s conversion.Scope) error {
	out.Deployed = in.Deployed
	return nil
}

// Convert_replay_SiloStatus_To_v1alpha1_SiloStatus is an autogenerated conversion function.
func Convert_replay_SiloStatus_To_v1alpha1_SiloStatus(in *replay.SiloStatus, out *SiloStatus, s conversion.Scope) error {
	return autoConvert_replay_SiloStatus_To_v1alpha1_SiloStatus(in, out, s)
}

func autoConvert_v1alpha1_StdoutOutput_To_replay_StdoutOutput(in *StdoutOutput, out *replay.StdoutOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_v1alpha1_StdoutOutput_To_replay_StdoutOutput is an autogenerated conversion function.
func Convert_v1alpha1_StdoutOutput_To_replay_StdoutOutput(in *StdoutOutput, out *replay.StdoutOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_StdoutOutput_To_replay_StdoutOutput(in, out, s)
}

func autoConvert_replay_StdoutOutput_To_v1alpha1_StdoutOutput(in *replay.StdoutOutput, out *StdoutOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	return nil
}

// Convert_replay_StdoutOutput_To_v1alpha1_StdoutOutput is an autogenerated conversion function.
func Convert_replay_StdoutOutput_To_v1alpha1_StdoutOutput(in *replay.StdoutOutput, out *StdoutOutput, s conversion.Scope) error {
	return autoConvert_replay_StdoutOutput_To_v1alpha1_StdoutOutput(in, out, s)
}

func autoConvert_v1alpha1_TcpOutput_To_replay_TcpOutput(in *TcpOutput, out *replay.TcpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_v1alpha1_TcpOutput_To_replay_TcpOutput is an autogenerated conversion function.
func Convert_v1alpha1_TcpOutput_To_replay_TcpOutput(in *TcpOutput, out *replay.TcpOutput, s conversion.Scope) error {
	return autoConvert_v1alpha1_TcpOutput_To_replay_TcpOutput(in, out, s)
}

func autoConvert_replay_TcpOutput_To_v1alpha1_TcpOutput(in *replay.TcpOutput, out *TcpOutput, s conversion.Scope) error {
	out.Enabled = in.Enabled
	out.Uri = in.Uri
	return nil
}

// Convert_replay_TcpOutput_To_v1alpha1_TcpOutput is an autogenerated conversion function.
func Convert_replay_TcpOutput_To_v1alpha1_TcpOutput(in *replay.TcpOutput, out *TcpOutput, s conversion.Scope) error {
	return autoConvert_replay_TcpOutput_To_v1alpha1_TcpOutput(in, out, s)
}
