// This file was automatically generated by lister-gen

package v1alpha1

// HarvesterListerExpansion allows custom methods to be added to
// HarvesterLister.
type HarvesterListerExpansion interface{}

// HarvesterNamespaceListerExpansion allows custom methods to be added to
// HarvesterNamespaceLister.
type HarvesterNamespaceListerExpansion interface{}

// RefineryListerExpansion allows custom methods to be added to
// RefineryLister.
type RefineryListerExpansion interface{}

// RefineryNamespaceListerExpansion allows custom methods to be added to
// RefineryNamespaceLister.
type RefineryNamespaceListerExpansion interface{}
