// This file was automatically generated by informer-gen

package v1alpha1

import (
	kubereplay_v1alpha1 "github.com/lwolf/kubereplay/pkg/apis/kubereplay/v1alpha1"
	"github.com/lwolf/kubereplay/pkg/client/clientset_generated/clientset"
	"github.com/lwolf/kubereplay/pkg/client/informers_generated/externalversions/internalinterfaces"
	"github.com/lwolf/kubereplay/pkg/client/listers_generated/kubereplay/v1alpha1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/tools/cache"
	"time"
)

// HarvesterInformer provides access to a shared informer and lister for
// Harvesters.
type HarvesterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HarvesterLister
}

type harvesterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHarvesterInformer constructs a new informer for Harvester type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHarvesterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHarvesterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHarvesterInformer constructs a new informer for Harvester type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHarvesterInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubereplayV1alpha1().Harvesters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubereplayV1alpha1().Harvesters(namespace).Watch(options)
			},
		},
		&kubereplay_v1alpha1.Harvester{},
		resyncPeriod,
		indexers,
	)
}

func (f *harvesterInformer) defaultInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHarvesterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *harvesterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubereplay_v1alpha1.Harvester{}, f.defaultInformer)
}

func (f *harvesterInformer) Lister() v1alpha1.HarvesterLister {
	return v1alpha1.NewHarvesterLister(f.Informer().GetIndexer())
}
