// This file was automatically generated by informer-gen

package v1alpha1

import (
	"github.com/lwolf/kubereplay/pkg/client/informers_generated/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Harvesters returns a HarvesterInformer.
	Harvesters() HarvesterInformer
	// Refineries returns a RefineryInformer.
	Refineries() RefineryInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Harvesters returns a HarvesterInformer.
func (v *version) Harvesters() HarvesterInformer {
	return &harvesterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Refineries returns a RefineryInformer.
func (v *version) Refineries() RefineryInformer {
	return &refineryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
